// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3853.Pridetronics2018.subsystems;

import org.usfirst.frc3853.Pridetronics2018.RobotMap;
import org.usfirst.frc3853.Pridetronics2018.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.DigitalInput;

import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

/**
 *
 */
public class Climb extends Subsystem {

  private final SpeedController climbMotor = RobotMap.climbMotor;

  // private final DigitalInput limitSwitchLift = RobotMap.limitSwitchLift;

  @Override
  public void initDefaultCommand() {

    // Set the default command for a subsystem here.
    // setDefaultCommand(new MySpecialCommand());
  }

  @Override
  public void periodic() {
    // Put code here to be run every loop

  }

  public void up() {
    ((SpeedController) climbMotor).set(1);
  }

  public void down() {
    ((SpeedController) climbMotor).set(-1);
  }

  public void stop() {
    ((SpeedController) climbMotor).set(0);
  }

  /*
   * public boolean limitSwitchOpen() { return !limitSwitchLift.get(); }
   */
  // Put methods for controlling this subsystem
  // here. Call these from Commands.

}
